const data = {
  title: "홈투데이",
  screen_name: "TODAY",
  view_event_logging: {},
  logging: {
    SCREEN: "TODAY",
  },
  components: [
    {
      component_id: 128,
      type: {
        header: null,
        item_list: "TWO_COL_CARD_LIST",
        footer: null,
      },
      logging: {
        analytics: {
          LIST_ID: "today_recommend",
        },
        ably_only_log: {
          list_id: "today_recommend",
        },
      },
      entity: {
        header: null,
        item_list: [
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 47509199,
                name: "부츠컷맛집🖤[3기장,-2XL] 브리니 반로우 스판 힙포켓 부츠컷 데님 얇은원단 빅사이즈 키큰녀 키작녀 하체보정",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/FfvJgc65xOw/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzllMDlhNjEwMzkyYWE4MWY1ZTExYzI1YTAwYWNjYWNhLmdpZg",
                market_sno: 14796,
                market_name: "미오",
                market_type: "셀럽",
                delivery_type: "shak",
                sell_count: 4626,
                discount_rate: 20,
                first_page_rendering: {
                  goods_name:
                    "부츠컷맛집🖤[3기장,-2XL] 브리니 반로우 스판 힙포켓 부츠컷 데님 얇은원단 빅사이즈 키큰녀 키작녀 하체보정",
                  market_name: "미오",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/WLnZAtA5enY/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwNjExXzE3NDk2MTIxNjE0NjQ3OTBtLmpwZWc",
                  market_image: null,
                  discount_rate: 20,
                  original_price: 30600,
                  price: 24500,
                },
                is_new: false,
                price: 24500,
                like: {
                  goods_sno: 47509199,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 3,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/47509199/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "데님",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 3,
                  pool: "basic_reco",
                  goods_sno: 47509199,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "47509199",
                  GOODS_NAME:
                    "부츠컷맛집🖤[3기장,-2XL] 브리니 반로우 스판 힙포켓 부츠컷 데님 얇은원단 빅사이즈 키큰녀 키작녀 하체보정",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "14796",
                  MARKET_NAME: "미오",
                  CATEGORY_SNO: "501",
                  CATEGORY_NAME: "데님",
                  STANDARD_CATEGORY_SNO: "75",
                  STANDARD_CATEGORY_NAME: "데님 롱팬츠",
                  DISCOUNT_RATE: 20,
                  SALES_PRICE: 24500,
                  SALES_PRICE_RANGE: "20,001~25,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "shak",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 429,
                  REVIEW_COUNT_RANGE: "401~450",
                  REVIEW_RATING: 98,
                  LIKES_COUNT: 16647,
                  LIKES_COUNT_RANGE: "16,601~16,650",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "TODAY_DELIVERY"],
                      [
                        "image_url",
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      ],
                      ["image_width", 46],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 3,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/FfvJgc65xOw/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzllMDlhNjEwMzkyYWE4MWY1ZTExYzI1YTAwYWNjYWNhLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "부츠컷맛집🖤[3기장,-2XL] 브리니 반로우 스판 힙포켓 부츠컷 데님 얇은원단 빅사이즈 키큰녀 키작녀 하체보정",
                  price: "24,500",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "20%",
                  closed_reason: null,
                  image_badge:
                    "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                  image_badge_width: 46,
                  image_badge_height: 18,
                  image_badge_list: [
                    {
                      type: "TODAY_DELIVERY",
                      image_url:
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      image_width: 46,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "미오",
                  nudging_text: "4,626개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 30137192,
                name: "가을🤎[하체커버,~2XL] 바게트 볼륨 옆핀턱 밑단 버튼 코튼 와이드 팬츠",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/n8DL2u0U9so/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzhlZWM3YWQ1YzdlYjkyNjRmZmYxZDE4ZGZiN2IyZWQ1LmdpZg",
                market_sno: 14796,
                market_name: "미오",
                market_type: "셀럽",
                delivery_type: "standard",
                sell_count: 18911,
                discount_rate: 20,
                first_page_rendering: {
                  goods_name:
                    "가을🤎[하체커버,~2XL] 바게트 볼륨 옆핀턱 밑단 버튼 코튼 와이드 팬츠",
                  market_name: "미오",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/cVZz_qJequs/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQxMDEyXzE3Mjg2NjM1MjQ2OTc0MzNtLmpwZWc",
                  market_image: null,
                  discount_rate: 20,
                  original_price: 34400,
                  price: 27500,
                },
                is_new: false,
                price: 27500,
                like: {
                  goods_sno: 30137192,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 4,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/30137192/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "롱팬츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 4,
                  pool: "basic_reco",
                  goods_sno: 30137192,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "30137192",
                  GOODS_NAME:
                    "가을🤎[하체커버,~2XL] 바게트 볼륨 옆핀턱 밑단 버튼 코튼 와이드 팬츠",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "14796",
                  MARKET_NAME: "미오",
                  CATEGORY_SNO: "176",
                  CATEGORY_NAME: "롱팬츠",
                  STANDARD_CATEGORY_SNO: "73",
                  STANDARD_CATEGORY_NAME: "롱팬츠",
                  DISCOUNT_RATE: 20,
                  SALES_PRICE: 27500,
                  SALES_PRICE_RANGE: "25,001~30,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 3237,
                  REVIEW_COUNT_RANGE: "3,201~3,250",
                  REVIEW_RATING: 95,
                  LIKES_COUNT: 42133,
                  LIKES_COUNT_RANGE: "42,101~42,150",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 4,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/n8DL2u0U9so/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzhlZWM3YWQ1YzdlYjkyNjRmZmYxZDE4ZGZiN2IyZWQ1LmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "가을🤎[하체커버,~2XL] 바게트 볼륨 옆핀턱 밑단 버튼 코튼 와이드 팬츠",
                  price: "27,500",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "20%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "미오",
                  nudging_text: "18,911개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 51434672,
                name: "[허리잘록핏] 카야 더블 레이어드 셔링 원오프 스판 긴팔티 가을옷 신상",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/x5_iA-VyTD0/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzdmN2M2YWMzNTFlYmNjNjk2MGI5ODFiNjFlZTVkNDQwLmdpZg",
                market_sno: 14796,
                market_name: "미오",
                market_type: "셀럽",
                delivery_type: "shak",
                sell_count: 643,
                discount_rate: 5,
                first_page_rendering: {
                  goods_name:
                    "[허리잘록핏] 카야 더블 레이어드 셔링 원오프 스판 긴팔티 가을옷 신상",
                  market_name: "미오",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/HgQt4YZ0YcY/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwODE0XzE3NTUxNjA5MTc3MTI4NTdtLmpwZWc",
                  market_image: null,
                  discount_rate: 5,
                  original_price: 18500,
                  price: 17500,
                },
                is_new: false,
                price: 17500,
                like: {
                  goods_sno: 51434672,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 5,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/51434672/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "긴소매티셔츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 5,
                  pool: "basic_reco",
                  goods_sno: 51434672,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "51434672",
                  GOODS_NAME:
                    "[허리잘록핏] 카야 더블 레이어드 셔링 원오프 스판 긴팔티 가을옷 신상",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "14796",
                  MARKET_NAME: "미오",
                  CATEGORY_SNO: "498",
                  CATEGORY_NAME: "긴소매티셔츠",
                  STANDARD_CATEGORY_SNO: "23",
                  STANDARD_CATEGORY_NAME: "긴소매티셔츠",
                  DISCOUNT_RATE: 5,
                  SALES_PRICE: 17500,
                  SALES_PRICE_RANGE: "15,001~20,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "shak",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 28,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 92,
                  LIKES_COUNT: 2831,
                  LIKES_COUNT_RANGE: "2,801~2,850",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "TODAY_DELIVERY"],
                      [
                        "image_url",
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      ],
                      ["image_width", 46],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 5,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/x5_iA-VyTD0/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzdmN2M2YWMzNTFlYmNjNjk2MGI5ODFiNjFlZTVkNDQwLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[허리잘록핏] 카야 더블 레이어드 셔링 원오프 스판 긴팔티 가을옷 신상",
                  price: "17,500",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "5%",
                  closed_reason: null,
                  image_badge:
                    "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                  image_badge_width: 46,
                  image_badge_height: 18,
                  image_badge_list: [
                    {
                      type: "TODAY_DELIVERY",
                      image_url:
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      image_width: 46,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "미오",
                  nudging_text: "643개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 51910408,
                name: "🚚당일발송🚚4color/사계절 - 비비 도트 벌룬 와이드 팬츠 -",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/XFRLSTmkQNI/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzkyODk2ODk3MmFiODBlOGUzOWQ4NDVkN2VmZmM4YzRhLmdpZg",
                market_sno: 36674,
                market_name: "비비투몽",
                market_type: "셀럽",
                delivery_type: "today",
                sell_count: 942,
                discount_rate: 0,
                first_page_rendering: {
                  goods_name:
                    "🚚당일발송🚚4color/사계절 - 비비 도트 벌룬 와이드 팬츠 -",
                  market_name: "비비투몽",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/brGK65dwUDI/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwODIyXzE3NTU4NDAwMDAyNzY4MzVtLmpwZw",
                  market_image: null,
                  discount_rate: 0,
                  original_price: 40700,
                  price: 40700,
                },
                is_new: false,
                price: 40700,
                like: {
                  goods_sno: 51910408,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 6,
                  },
                },
                ad: {
                  list_id: "recommend",
                  campaign_id: "297025",
                  parameters:
                    '{"generated_at": "2025-09-19 16:51:03", "market_sno": 36674, "ad_market_sno": 12903, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2QYx4s/YjObGUS40WUIs8cN9RBI5BdQdnrCoPJclaO4fTkzc+XLqZy6p6YT7qqk/PEQwswGNWoVaZjDYaZO6LRc3nQaXHB1Ohdd/ykPHRzaBGq/MUbzSa8lEO6Byb3UAFLmnB2TgGTz3eM4sIsFExtfu4Ccz70Qc47ubBZEGUVZ72eyu5SIeA6pNiCXbuUmNSuXGEW+A3lVwSUwfLwTvg2KXszhsiX5laBT09oobyxe1kBaIsLxUqyMTjUF/SzxwDREwikCJhGX1KamK0Kj/cijhbsvPjvzCvzbrNQM/rBjF/Q==", "list_index": 6}',
                  goods_sno: 51910408,
                },
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/51910408/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "롱팬츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 6,
                  pool: "ad",
                  goods_sno: 51910408,
                  ad: {
                    list_id: "recommend",
                    campaign_id: "297025",
                    parameters:
                      '{"generated_at": "2025-09-19 16:51:03", "market_sno": 36674, "ad_market_sno": 12903, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2QYx4s/YjObGUS40WUIs8cN9RBI5BdQdnrCoPJclaO4fTkzc+XLqZy6p6YT7qqk/PEQwswGNWoVaZjDYaZO6LRc3nQaXHB1Ohdd/ykPHRzaBGq/MUbzSa8lEO6Byb3UAFLmnB2TgGTz3eM4sIsFExtfu4Ccz70Qc47ubBZEGUVZ72eyu5SIeA6pNiCXbuUmNSuXGEW+A3lVwSUwfLwTvg2KXszhsiX5laBT09oobyxe1kBaIsLxUqyMTjUF/SzxwDREwikCJhGX1KamK0Kj/cijhbsvPjvzCvzbrNQM/rBjF/Q==", "list_index": 6}',
                    goods_sno: 51910408,
                  },
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "51910408",
                  GOODS_NAME:
                    "🚚당일발송🚚4color/사계절 - 비비 도트 벌룬 와이드 팬츠 -",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "36674",
                  MARKET_NAME: "비비투몽",
                  CATEGORY_SNO: "176",
                  CATEGORY_NAME: "롱팬츠",
                  STANDARD_CATEGORY_SNO: "73",
                  STANDARD_CATEGORY_NAME: "롱팬츠",
                  DISCOUNT_RATE: 0,
                  SALES_PRICE: 40700,
                  SALES_PRICE_RANGE: "40,001~45,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "today",
                  IS_AD: "1",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 29,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 100,
                  LIKES_COUNT: 4370,
                  LIKES_COUNT_RANGE: "4,351~4,400",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "TODAY_DELIVERY"],
                      [
                        "image_url",
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      ],
                      ["image_width", 46],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 6,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/XFRLSTmkQNI/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzkyODk2ODk3MmFiODBlOGUzOWQ4NDVkN2VmZmM4YzRhLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "🚚당일발송🚚4color/사계절 - 비비 도트 벌룬 와이드 팬츠 -",
                  price: "40,700",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: null,
                  closed_reason: null,
                  image_badge:
                    "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                  image_badge_width: 46,
                  image_badge_height: 18,
                  image_badge_list: [
                    {
                      type: "TODAY_DELIVERY",
                      image_url:
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      image_width: 46,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "비비투몽",
                  nudging_text: "942개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 51223536,
                name: "[일체형] 에스핀 백 레터링 후크 롱팬츠",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/onFmmYhL8_U/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2EzMTM1YWYyZjEwNmQ5ZDc0NDYyNTNjYjE5ODYyNmFhLmdpZg",
                market_sno: 7389,
                market_name: "프레첼",
                market_type: "셀럽",
                delivery_type: "standard",
                sell_count: 123,
                discount_rate: 52,
                first_page_rendering: {
                  goods_name: "[일체형] 에스핀 백 레터링 후크 롱팬츠",
                  market_name: "프레첼",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/7NZNPzIW15c/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwODA4XzE3NTQ2MzQxNDg1NTY4MTdtLnBuZw",
                  market_image: null,
                  discount_rate: 52,
                  original_price: 65000,
                  price: 30780,
                },
                is_new: false,
                price: 30780,
                like: {
                  goods_sno: 51223536,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 7,
                  },
                },
                ad: {
                  list_id: "recommend",
                  campaign_id: "499501",
                  parameters:
                    '{"generated_at": "2025-09-19 16:51:03", "market_sno": 7389, "ad_market_sno": 2214, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2QYP5Iy/72YFqz6ZPukK1WOjWF1loCoQ8o/K5O/AwVTjD0KgWUyEJSl8cU1oySY1mQJH6z5+0AY0jz90CZeN51VZfwKsnfNx6AhhHFJGFwGKo8fBuWlALnvA03wYQqfWwZVwMaJXFmAUV7XeUCJThJQUbgRYcCZguoIlr4RIr+DNgVpx+zhJLy2XdqOEsplFZdaztXckY6EUkxV1yZLfSCqg4pfGmSPNlFMLm5eq4NPv1nPEK5K+n7N5Zp6V0ujA9LsyM/MtUEg5JKLu7vNBHyOM4gL7jWAVjgBo/DZ7ZXbGLA==", "list_index": 7}',
                  goods_sno: 51223536,
                },
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/51223536/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "롱팬츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 7,
                  pool: "ad",
                  goods_sno: 51223536,
                  ad: {
                    list_id: "recommend",
                    campaign_id: "499501",
                    parameters:
                      '{"generated_at": "2025-09-19 16:51:03", "market_sno": 7389, "ad_market_sno": 2214, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2QYP5Iy/72YFqz6ZPukK1WOjWF1loCoQ8o/K5O/AwVTjD0KgWUyEJSl8cU1oySY1mQJH6z5+0AY0jz90CZeN51VZfwKsnfNx6AhhHFJGFwGKo8fBuWlALnvA03wYQqfWwZVwMaJXFmAUV7XeUCJThJQUbgRYcCZguoIlr4RIr+DNgVpx+zhJLy2XdqOEsplFZdaztXckY6EUkxV1yZLfSCqg4pfGmSPNlFMLm5eq4NPv1nPEK5K+n7N5Zp6V0ujA9LsyM/MtUEg5JKLu7vNBHyOM4gL7jWAVjgBo/DZ7ZXbGLA==", "list_index": 7}',
                    goods_sno: 51223536,
                  },
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "51223536",
                  GOODS_NAME: "[일체형] 에스핀 백 레터링 후크 롱팬츠",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "7389",
                  MARKET_NAME: "프레첼",
                  CATEGORY_SNO: "176",
                  CATEGORY_NAME: "롱팬츠",
                  STANDARD_CATEGORY_SNO: "73",
                  STANDARD_CATEGORY_NAME: "롱팬츠",
                  DISCOUNT_RATE: 52,
                  SALES_PRICE: 30780,
                  SALES_PRICE_RANGE: "30,001~35,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "1",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 4,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 75,
                  LIKES_COUNT: 811,
                  LIKES_COUNT_RANGE: "801~850",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 7,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/onFmmYhL8_U/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2EzMTM1YWYyZjEwNmQ5ZDc0NDYyNTNjYjE5ODYyNmFhLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[일체형] 에스핀 백 레터링 후크 롱팬츠",
                  price: "30,780",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "52%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "프레첼",
                  nudging_text: "123개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 51478587,
                name: "가을🤎[2기장,-2XL] 하쿠 빈티지 워싱 절개 롱 데님 스커트 하체커버 키큰녀 키작녀",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/EEdc8ME5gnk/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2Q3M2FmZWJiYmVjZTFhNWY5YjA4MDg0MGVlNDJhOGRhLmdpZg",
                market_sno: 14796,
                market_name: "미오",
                market_type: "셀럽",
                delivery_type: "shak",
                sell_count: 920,
                discount_rate: 20,
                first_page_rendering: {
                  goods_name:
                    "가을🤎[2기장,-2XL] 하쿠 빈티지 워싱 절개 롱 데님 스커트 하체커버 키큰녀 키작녀",
                  market_name: "미오",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/keSzEKCZ67o/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwODEzXzE3NTUwNjQ0MDkxMDI5NjNtLkpQRUc",
                  market_image: null,
                  discount_rate: 20,
                  original_price: 30600,
                  price: 24500,
                },
                is_new: false,
                price: 24500,
                like: {
                  goods_sno: 51478587,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 8,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/51478587/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "미디/롱스커트",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 8,
                  pool: "basic_reco",
                  goods_sno: 51478587,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "51478587",
                  GOODS_NAME:
                    "가을🤎[2기장,-2XL] 하쿠 빈티지 워싱 절개 롱 데님 스커트 하체커버 키큰녀 키작녀",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "14796",
                  MARKET_NAME: "미오",
                  CATEGORY_SNO: "205",
                  CATEGORY_NAME: "미디/롱스커트",
                  STANDARD_CATEGORY_SNO: "82",
                  STANDARD_CATEGORY_NAME: "데님 롱스커트",
                  DISCOUNT_RATE: 20,
                  SALES_PRICE: 24500,
                  SALES_PRICE_RANGE: "20,001~25,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "shak",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 50,
                  REVIEW_COUNT_RANGE: "51~100",
                  REVIEW_RATING: 98,
                  LIKES_COUNT: 3029,
                  LIKES_COUNT_RANGE: "3,001~3,050",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "TODAY_DELIVERY"],
                      [
                        "image_url",
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      ],
                      ["image_width", 46],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 8,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/EEdc8ME5gnk/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2Q3M2FmZWJiYmVjZTFhNWY5YjA4MDg0MGVlNDJhOGRhLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "가을🤎[2기장,-2XL] 하쿠 빈티지 워싱 절개 롱 데님 스커트 하체커버 키큰녀 키작녀",
                  price: "24,500",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "20%",
                  closed_reason: null,
                  image_badge:
                    "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                  image_badge_width: 46,
                  image_badge_height: 18,
                  image_badge_list: [
                    {
                      type: "TODAY_DELIVERY",
                      image_url:
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      image_width: 46,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "미오",
                  nudging_text: "920개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 50771477,
                name: "[LOO⭐P/MADE] 엔젤 스타 절개라인 조거 와이드 트레이닝 롱팬츠",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/e3WKGXBlIeU/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2ZmNDNlZTBhNmYxMjBhOWVhMDdkMTkwNTE2NzczZGM5LmdpZg",
                market_sno: 4036,
                market_name: "루너프",
                market_type: "셀럽",
                delivery_type: "today",
                sell_count: 6318,
                discount_rate: 25,
                first_page_rendering: {
                  goods_name:
                    "[LOO⭐P/MADE] 엔젤 스타 절개라인 조거 와이드 트레이닝 롱팬츠",
                  market_name: "루너프",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/cy0DNyAb5i0/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwODA0XzE3NTQzMDE3Nzc1MTgzNTRtLmpwZw",
                  market_image: null,
                  discount_rate: 25,
                  original_price: 33000,
                  price: 24710,
                },
                is_new: false,
                price: 24710,
                like: {
                  goods_sno: 50771477,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 9,
                  },
                },
                ad: {
                  list_id: "recommend",
                  campaign_id: "482377",
                  parameters:
                    '{"generated_at": "2025-09-19 16:51:03", "market_sno": 4036, "ad_market_sno": 1675, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2QbOBYN1Ik5H9HgLcLhFRKA9IkEoIHlDLRqguR4YjU5kIxStbuuOjXdYaLlRbtFo/gcgLBp1RnBbT340adIIv+GbX/giLSZZL1RErTRka1Luo3wne3OXp+xyktHiHYs6oQJbsJ0KmKNCcv28R+PSKRqD184hRykvNeK9tPismZdNKEHskbFKvWZkaoofILtcERt/yHW3iLDOy192eiL7tO5GcLsKVrEOkXNEWvB++o96yo61x9ro8ndn2laOmcAzki5AtV/JyqvdWkRz0vKw2kNl1dp4kEMbP2jKw3Z4DR3AXQ==", "list_index": 9}',
                  goods_sno: 50771477,
                },
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/50771477/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "롱팬츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 9,
                  pool: "ad",
                  goods_sno: 50771477,
                  ad: {
                    list_id: "recommend",
                    campaign_id: "482377",
                    parameters:
                      '{"generated_at": "2025-09-19 16:51:03", "market_sno": 4036, "ad_market_sno": 1675, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2QbOBYN1Ik5H9HgLcLhFRKA9IkEoIHlDLRqguR4YjU5kIxStbuuOjXdYaLlRbtFo/gcgLBp1RnBbT340adIIv+GbX/giLSZZL1RErTRka1Luo3wne3OXp+xyktHiHYs6oQJbsJ0KmKNCcv28R+PSKRqD184hRykvNeK9tPismZdNKEHskbFKvWZkaoofILtcERt/yHW3iLDOy192eiL7tO5GcLsKVrEOkXNEWvB++o96yo61x9ro8ndn2laOmcAzki5AtV/JyqvdWkRz0vKw2kNl1dp4kEMbP2jKw3Z4DR3AXQ==", "list_index": 9}',
                    goods_sno: 50771477,
                  },
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "50771477",
                  GOODS_NAME:
                    "[LOO⭐P/MADE] 엔젤 스타 절개라인 조거 와이드 트레이닝 롱팬츠",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "4036",
                  MARKET_NAME: "루너프",
                  CATEGORY_SNO: "176",
                  CATEGORY_NAME: "롱팬츠",
                  STANDARD_CATEGORY_SNO: "73",
                  STANDARD_CATEGORY_NAME: "롱팬츠",
                  DISCOUNT_RATE: 25,
                  SALES_PRICE: 24710,
                  SALES_PRICE_RANGE: "20,001~25,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "today",
                  IS_AD: "1",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 277,
                  REVIEW_COUNT_RANGE: "251~300",
                  REVIEW_RATING: 96,
                  LIKES_COUNT: 26173,
                  LIKES_COUNT_RANGE: "26,151~26,200",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "TODAY_DELIVERY"],
                      [
                        "image_url",
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      ],
                      ["image_width", 46],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 9,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/e3WKGXBlIeU/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2ZmNDNlZTBhNmYxMjBhOWVhMDdkMTkwNTE2NzczZGM5LmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[LOO⭐P/MADE] 엔젤 스타 절개라인 조거 와이드 트레이닝 롱팬츠",
                  price: "24,710",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "25%",
                  closed_reason: null,
                  image_badge:
                    "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                  image_badge_width: 46,
                  image_badge_height: 18,
                  image_badge_list: [
                    {
                      type: "TODAY_DELIVERY",
                      image_url:
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      image_width: 46,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "루너프",
                  nudging_text: "6,318개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 10238578,
                name: "색상추가✨[숏,기본,롱][S~2XL] vintage stone washing slim bootcut denim! 4col",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/3l3kmrxlP8g/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzNlYzliMjEwNGYwNGFiNTAzNTU4YzhlODkxN2I3YjM3LmdpZg",
                market_sno: 14796,
                market_name: "미오",
                market_type: "셀럽",
                delivery_type: "shak",
                sell_count: 106296,
                discount_rate: 4,
                first_page_rendering: {
                  goods_name:
                    "색상추가✨[숏,기본,롱][S~2XL] vintage stone washing slim bootcut denim! 4col",
                  market_name: "미오",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/rz-9mqyNUIA/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQwMjI2XzE3MDg5MjY3NTIzMDE3NjBtLmpwZWc",
                  market_image: null,
                  discount_rate: 4,
                  original_price: 24500,
                  price: 23500,
                },
                is_new: false,
                price: 23500,
                like: {
                  goods_sno: 10238578,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 10,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/10238578/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "데님",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 10,
                  pool: "basic_reco",
                  goods_sno: 10238578,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "10238578",
                  GOODS_NAME:
                    "색상추가✨[숏,기본,롱][S~2XL] vintage stone washing slim bootcut denim! 4col",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "14796",
                  MARKET_NAME: "미오",
                  CATEGORY_SNO: "501",
                  CATEGORY_NAME: "데님",
                  STANDARD_CATEGORY_SNO: "75",
                  STANDARD_CATEGORY_NAME: "데님 롱팬츠",
                  DISCOUNT_RATE: 4,
                  SALES_PRICE: 23500,
                  SALES_PRICE_RANGE: "20,001~25,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "shak",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 27644,
                  REVIEW_COUNT_RANGE: "27,601~27,650",
                  REVIEW_RATING: 97,
                  LIKES_COUNT: 153107,
                  LIKES_COUNT_RANGE: "153,101~153,150",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "TODAY_DELIVERY"],
                      [
                        "image_url",
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      ],
                      ["image_width", 46],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 10,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/3l3kmrxlP8g/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzNlYzliMjEwNGYwNGFiNTAzNTU4YzhlODkxN2I3YjM3LmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "색상추가✨[숏,기본,롱][S~2XL] vintage stone washing slim bootcut denim! 4col",
                  price: "23,500",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "4%",
                  closed_reason: null,
                  image_badge:
                    "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                  image_badge_width: 46,
                  image_badge_height: 18,
                  image_badge_list: [
                    {
                      type: "TODAY_DELIVERY",
                      image_url:
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      image_width: 46,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "미오",
                  nudging_text: "106,296개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 38748093,
                name: "핀터룩✨[3기장,~2XL] 워크 뒷절개 하이웨스트 일자 와이드 팬츠",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/Iil6iGe9cIQ/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzQzMmI1ZTAyMDZkOWY2YTk5ZjBmOTY3YjI2NTUyYjIxLmdpZg",
                market_sno: 14796,
                market_name: "미오",
                market_type: "셀럽",
                delivery_type: "shak",
                sell_count: 4125,
                discount_rate: 4,
                first_page_rendering: {
                  goods_name:
                    "핀터룩✨[3기장,~2XL] 워크 뒷절개 하이웨스트 일자 와이드 팬츠",
                  market_name: "미오",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/GlDhJOKYG48/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwMTI1XzE3Mzc3NDA0MzkxNjg5OThtLmpwZWc",
                  market_image: null,
                  discount_rate: 4,
                  original_price: 22500,
                  price: 21500,
                },
                is_new: false,
                price: 21500,
                like: {
                  goods_sno: 38748093,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 11,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/38748093/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "롱팬츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 11,
                  pool: "basic_reco",
                  goods_sno: 38748093,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "38748093",
                  GOODS_NAME:
                    "핀터룩✨[3기장,~2XL] 워크 뒷절개 하이웨스트 일자 와이드 팬츠",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "14796",
                  MARKET_NAME: "미오",
                  CATEGORY_SNO: "176",
                  CATEGORY_NAME: "롱팬츠",
                  STANDARD_CATEGORY_SNO: "73",
                  STANDARD_CATEGORY_NAME: "롱팬츠",
                  DISCOUNT_RATE: 4,
                  SALES_PRICE: 21500,
                  SALES_PRICE_RANGE: "20,001~25,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "shak",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 573,
                  REVIEW_COUNT_RANGE: "551~600",
                  REVIEW_RATING: 96,
                  LIKES_COUNT: 10682,
                  LIKES_COUNT_RANGE: "10,651~10,700",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "TODAY_DELIVERY"],
                      [
                        "image_url",
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      ],
                      ["image_width", 46],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 11,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/Iil6iGe9cIQ/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzQzMmI1ZTAyMDZkOWY2YTk5ZjBmOTY3YjI2NTUyYjIxLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "핀터룩✨[3기장,~2XL] 워크 뒷절개 하이웨스트 일자 와이드 팬츠",
                  price: "21,500",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "4%",
                  closed_reason: null,
                  image_badge:
                    "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                  image_badge_width: 46,
                  image_badge_height: 18,
                  image_badge_list: [
                    {
                      type: "TODAY_DELIVERY",
                      image_url:
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      image_width: 46,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "미오",
                  nudging_text: "4,125개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 4570858,
                name: "[12만장돌파💎허리조절💎와이드팬츠] 🌈투스트랩 와이드 팬츠🌈 +6컬러 (비조,버클,면바지,코튼와이드,코튼팬츠,스트랩팬츠,화이트팬츠,흰바지,면팬츠)",
                image:
                  "https://d3ha2047wt6x28.cloudfront.net/4N9XoqF4oQs/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2RhYWRhMTI0Njg5ZmJkM2M4M2JkM2NkMmFkZDEyZWJhLmpwZw",
                market_sno: 20592,
                market_name: "고고싱",
                market_type: "쇼핑몰",
                delivery_type: "today",
                sell_count: 111765,
                discount_rate: 16,
                first_page_rendering: {
                  goods_name:
                    "[12만장돌파💎허리조절💎와이드팬츠] 🌈투스트랩 와이드 팬츠🌈 +6컬러 (비조,버클,면바지,코튼와이드,코튼팬츠,스트랩팬츠,화이트팬츠,흰바지,면팬츠)",
                  market_name: "고고싱",
                  cover_image:
                    "https://d3ha2047wt6x28.cloudfront.net/DwQ3uDl9HII/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwOTE5XzE3NTgyNjYxNjQyOTMzNDVtLnBuZw",
                  market_image: null,
                  discount_rate: 16,
                  original_price: 35900,
                  price: 29900,
                },
                is_new: false,
                price: 29900,
                like: {
                  goods_sno: 4570858,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 12,
                  },
                },
                ad: {
                  list_id: "recommend",
                  campaign_id: "425245",
                  parameters:
                    '{"generated_at": "2025-09-19 16:51:03", "market_sno": 20592, "ad_market_sno": 3820, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2QYKjKkV/VmGC+B5yXxCEbQGD+idLhwtmkCOCgLXOIpkQRCpJFSmhPWmH9WAvGaqxwsQUYbXUeQLHIDSwVvVKsdUDUZ4oNXyETH8lXwZx0pHS/34iM4elcaqF+ixEEBuqEhp/x/dRsFae5wZvAzbzqVXzAtFy3UsR16qvApS3uhbI5g0i6oBhxFokg0ZfwdFQLUiINyCH/Uc/YLWBbJhGP+w6j2Q8djKFT89MUjlcBFPTWYk6wGrZMqoQPunaPxvB23o1spQ1RzfFYVzovWe7P+Mgmj9ew/Fr8veIwi5oq2FCw==", "list_index": 12}',
                  goods_sno: 4570858,
                },
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/4570858/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "롱팬츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 12,
                  pool: "ad",
                  goods_sno: 4570858,
                  ad: {
                    list_id: "recommend",
                    campaign_id: "425245",
                    parameters:
                      '{"generated_at": "2025-09-19 16:51:03", "market_sno": 20592, "ad_market_sno": 3820, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2QYKjKkV/VmGC+B5yXxCEbQGD+idLhwtmkCOCgLXOIpkQRCpJFSmhPWmH9WAvGaqxwsQUYbXUeQLHIDSwVvVKsdUDUZ4oNXyETH8lXwZx0pHS/34iM4elcaqF+ixEEBuqEhp/x/dRsFae5wZvAzbzqVXzAtFy3UsR16qvApS3uhbI5g0i6oBhxFokg0ZfwdFQLUiINyCH/Uc/YLWBbJhGP+w6j2Q8djKFT89MUjlcBFPTWYk6wGrZMqoQPunaPxvB23o1spQ1RzfFYVzovWe7P+Mgmj9ew/Fr8veIwi5oq2FCw==", "list_index": 12}',
                    goods_sno: 4570858,
                  },
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "4570858",
                  GOODS_NAME:
                    "[12만장돌파💎허리조절💎와이드팬츠] 🌈투스트랩 와이드 팬츠🌈 +6컬러 (비조,버클,면바지,코튼와이드,코튼팬츠,스트랩팬츠,화이트팬츠,흰바지,면팬츠)",
                  MARKET_TYPE: "쇼핑몰",
                  MARKET_SNO: "20592",
                  MARKET_NAME: "고고싱",
                  CATEGORY_SNO: "176",
                  CATEGORY_NAME: "롱팬츠",
                  STANDARD_CATEGORY_SNO: "73",
                  STANDARD_CATEGORY_NAME: "롱팬츠",
                  DISCOUNT_RATE: 16,
                  SALES_PRICE: 29900,
                  SALES_PRICE_RANGE: "25,001~30,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "today",
                  IS_AD: "1",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "8",
                  REVIEW_COUNT: 16968,
                  REVIEW_COUNT_RANGE: "16,951~17,000",
                  REVIEW_RATING: 96,
                  LIKES_COUNT: 249789,
                  LIKES_COUNT_RANGE: "249,751~249,800",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "TODAY_DELIVERY"],
                      [
                        "image_url",
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      ],
                      ["image_width", 46],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 12,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/4N9XoqF4oQs/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2RhYWRhMTI0Njg5ZmJkM2M4M2JkM2NkMmFkZDEyZWJhLmpwZw",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[12만장돌파💎허리조절💎와이드팬츠] 🌈투스트랩 와이드 팬츠🌈 +6컬러 (비조,버클,면바지,코튼와이드,코튼팬츠,스트랩팬츠,화이트팬츠,흰바지,면팬츠)",
                  price: "29,900",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "16%",
                  closed_reason: null,
                  image_badge:
                    "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                  image_badge_width: 46,
                  image_badge_height: 18,
                  image_badge_list: [
                    {
                      type: "TODAY_DELIVERY",
                      image_url:
                        "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      image_width: 46,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "고고싱",
                  nudging_text: "111,765개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
        ],
        footer: null,
      },
    },
  ],
  next_token: "eyJsaSI6IDIsICJuIjogImV5SnNZWE4wWDJsdVpHVjRJam9nTVROOSJ9",
  view_event_channels: [
    "firebase",
    "amplitude",
    "ablylog",
    "facebook",
    "appsflyer",
  ],
};

// 1. 옷 이름이랑 브랜드 마켓 이름, 판매된 수

const itemlist = data.components
  .map((v) => v.entity.item_list)
  .flat()
  .map((v) => v.item_entity.item)
  .map((v) => ({
    name: v.name,
    market_name: v.market_name,
    sell_count: v.sell_count,
  }));
console.log(itemlist);
